# Generated by Django 2.2 on 2022-06-28 07:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20220628_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10, message='Поставьте оценку в диапазоне от 0 до 10')]),
        ),
    ]
